<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="objectmodelling" nsURI="objectmodelling" nsPrefix="objectmodelling">
  <eClassifiers xsi:type="ecore:EClass" name="ObjectModel" eSuperTypes="../../common/model/graph.ecore#//Graph"/>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="../../common/model/graph.ecore#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="../../common/model/graph.ecore#//Edge"/>
</ecore:EPackage>
